### ISSUE TITLE
Simulate errors during PCR process

### ISSUE THREAD

**Issue by vladimirkovacevic** [Fenrir996/IluminaPairEndReadSimulator#2]
Can you add errors on reads that would simulate their appearance during PCR Process? For example, after 2 PCR cycles one [branch](https://i.ytimg.com/vi/q27r-ZBw9lI/maxresdefault.jpg) of reads? If too complicated never mind.

**Comment by Fenrir996** [comment]
Will talk to colleagues

**Comment by Fenrir996** [comment]
Due to lack of time, given our work schedules and other university projects we've decided to neglect this since it isn't something that's crucial at this point
