### ISSUE TITLE
Add parameters of sequence_simulator() as command line arguments

### ISSUE THREAD

**Issue by vladimirkovacevic** [Fenrir996/IluminaPairEndReadSimulator#4]
...to allow the user to run the simulator from the command line. Fasta file can be mandatory, without differentiator, and for other add differentiators so the command line parser could recognize it. Similar interface as bwa-mem and bowtie2 have. Add also default values for every parameter.

**Comment by Fenrir996** [comment]
Issue has been noted and assigned to a collaborator

**Comment by mjovanovic1905** [comment]
Issue closed with [latest comit](https://github.com/Fenrir996/IluminaPairEndReadSimulator/commit/df830b191684d34183241a01a833495ee936ab80)
