### ISSUE TITLE
Add more comments in the code

### ISSUE THREAD

**Issue by vladimirkovacevic** [Fenrir996/IluminaPairEndReadSimulator#5]
This code is lacking comments.

**Comment by Fenrir996** [comment]
Noted

**Comment by vladimirkovacevic** [comment]
@Fenrir996 The SOP here would be to add comments first and then close the issue by posting the commit ID of the patch that adds the comments.

**Comment by Fenrir996** [comment]
Understood

**Comment by Fenrir996** [comment]
Code has been commented to a degree, Commit : 766d5fb
